addons:
 apt:
   packages:
    - clang-3.5
    - lib32stdc++6
    - lib32z1-dev
    - libc6-dev-i386
    - linux-libc-dev
    - g++-multilib
    - g++4.8
   sources:
    - llvm-toolchain-precise-3.5
    - ubuntu-toolchain-r-test
language: cpp
sudo: false
compiler:
 - clang
before_script:
 - CHECKOUT_DIR=$PWD && cd .. && $CHECKOUT_DIR/tools/checkout-deps.sh && cd $CHECKOUT_DIR
script:
 - mkdir obj-release && cd obj-release
 - PATH="~/.local/bin:$PATH"
 - CC=clang-3.5 CXX=clang-3.5 python ../configure.py --enable-optimize
 - ambuild
 - ./testing/test-all.sh
